### ISSUE TITLE
Map docs.darklang.com to here

### ISSUE THREAD

**Issue by avdi** [darklang/docs#101]
![image](https://user-images.githubusercontent.com/982/80550262-23a6a180-8985-11ea-9fc2-bbdd4df981c0.png)

The internal overlords request a 301 to https://darklang.github.io/docs/introduction please

**Comment by jceipek** [comment]
Thanks! We're planning to host the docs at `https://darklang.com/docs/*` soon.

**Comment by pbiggar** [comment]
Done, thanks for the report!
