### ISSUE TITLE
Error in getting started guide

### ISSUE THREAD

**Issue by joshuayoerger** [darklang/docs#15]
In the getting started guide (docs/docs/getting-started-tutorial.md) the screenshot for the first datastore (step 5.) shows a String and a Date db type. This should be Dict and Date as pictured in step 10.

![](https://darklang.github.io/docs/docs/assets/gettingstarted/Screen_Shot_2020-02-11_at_10.49.55_AM.png)

If it would be helpful, I am happy to create a new image and submit a pull request.

Thanks!

**Comment by vkrauchunas** [comment]
Thanks for reporting this, @joshuayoerger! Always feel free to open a PR if you'd prefer. :)
