### ISSUE TITLE
First Step in the tutorial indicates that you can click on "new HTTP handler named /hello" when this is not the case

### ISSUE THREAD

**Issue by abryden** [darklang/docs#205]
You can only use the arrow keys to select HTTP handler, DB, function, worker, cron, REPL - clicking does not work. 

![image](https://user-images.githubusercontent.com/2320326/98012693-041e8480-1dbf-11eb-9574-1b4a09f06d13.png)

If this is supposed to work by clicking this should be a bug at https://github.com/darklang/dark

**Comment by pbiggar** [comment]
You don't see something like this:

![image](https://user-images.githubusercontent.com/181762/98013774-cc1c3f00-1dc8-11eb-8f52-68f5bd1e4613.png)

**Comment by abryden** [comment]
That is exactly what I see: 
![image](https://user-images.githubusercontent.com/2320326/98015257-341b5700-1dc2-11eb-8411-2e8912d97943.png)

The issue is that the tutorial indicates you can both click and use the arrows + enter key. I can only use the arrows and enter key and not the mouse to select the New HTTP hander option.

**Comment by pbiggar** [comment]
Ah, I see. I can repro that, thanks!

**Comment by pbiggar** [comment]
Closing as the editor is no longer the desired way to use dark in future.
