### ISSUE TITLE
Search not yielding expected results

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/docs#237]
In looking at darklang/dark/issues/3697, I did some basic searches in the docs site, and got disappointing results
![image](https://user-images.githubusercontent.com/906686/163831468-7a0132bd-c5b9-44c5-bdac-62af213fe33f.png)

I see "Create a tool in REPL" on the left, so would expect at least that returned.

**Comment by pbiggar** [comment]
I can replicate this. I tried some searches on the algolia console and those worked fine, so it must be something to do with how we have it hooked up.

**Comment by pbiggar** [comment]
The console shows the requests coming in, but they all have a click-through-rate of 0%

**Comment by pbiggar** [comment]
@kate-grant did some research:

- Algolia search on Dark docs return "no results" for all searches
- It seems that Dark docs is indexed by Algolia
- Algolia is receiving search terms (recent searches show up in Algolia dashboard)
- Requests are being sent from Docusaurus/Dark docs
- Algolia support says the [facetFilters](https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/) are incorrect--the payload shows ["language:en",["docusaurus_tag:default","docusaurus_tag:docs-default-current"]]"
- Algolia support recommended adding a docusaurus_tag as an attributeForFaceting--they said to to open a PR to do this in the config
- [This](https://github.com/algolia/docsearch-configs/blob/master/configs/darklang.json) is the config for Dark docs--it is owned by Algolia and is archived. (The [docusarus config](https://github.com/darklang/docs/blob/main/docusaurus.config.js) in Dark docs has the Algolia credentials and they are correct)

**Comment by pbiggar** [comment]
Search should work now, thanks to some heroic work by @kate-grant
