### ISSUE TITLE
Darklang Release 9

### ISSUE THREAD

**Issue by pbiggar** [darklang/docs#321]
- [x] create and fill in a new set of release notes
  - [x] create a new `release-n.md` page in `docs/changelog`
  - [x] use [the `dark-changelog` canvas](https://darklang.com/a/dark-changelog)
        to fill in a draft of the changelog this gather PRs merged throughout the month
  - [x] add reference to new page in sidebar
  - [x] create headers; move bullets to appropriate headers
  - [x] merge similar bullets where relevant
  - [x] revise wording
  - [x] review each item and fill in changelog with images, diagrams, screen recordings, etc.
  - [x] were there any emergencies (i.e. service interruptions) throughout the
        month? are they worth documenting within the changelog or during our normal release cycle? Check `#status` and `#operations` in Discord, for reference.
- [x] update docs with anything we've done in the past month (if there's not much, just edit it in the main PR; otherwise updating docs in separate PRs might make sense)
- [x] merge changelog and docs updates
- [x] release review
  - [x] record video/audio
  - [x] upload to youtube/unlisted
  - [x] minor editing?
  - [x] publish
- [x] prepare drafts
  - [x] draft blog post
    - [x] review each changelog item to see if it should be highlighted
    - [x] consider
      - [x] what were the major themes of the month?
      - [x] what's immediately useful to our users?
      - [x] what interesting technical challenges did we face?
    - [x] can we link to any new docs/features?
    - [x] can we include any images or gifs?
    - [x] what header image should we use? with link
    - [x] include commented out links to Lobstrs, HN, Twitter, Mastodon, reddit,
          youtube, twitch, discord
  - [x] draft email
    - [x] create mailchimp campaign
    - [x] write draft
  - [x] draft
        [tweet](https://twitter.com/darklang)/[toot](https://devtools.social/@darklang)
  - [x] draft [HN](https://news.ycombinator.com/submit)
  - [x] draft [r/darklang](https://reddit.com/r/darklang)
  - [x] draft [Lobstrs](https://lobste.rs/stories/new)
  - [x] draft
        [discord #announcements](https://discord.com/channels/1015413734153388094/1015432022489043025)
  - [x] draft
        [Slack #announcements](https://darkcommunity.slack.com/archives/CP22G0GSJ)
- [x] publish blog post
- [x] post to socials
  - [x] send tweet
  - [x] send toot
  - [x] post HN
  - [x] post r/darklang
  - [x] post Lobstrs
  - [x] post discord
  - [x] post slack \#announcements
- [x] update blog post with links
  - [x] twitter
  - [x] mastodon
  - [x] reddit
  - [x] HN
  - [x] Lobstrs
  - [x] discord
- [x] link back to blog
  - [x] youtube
  - [x] changelog
- [x] send mailchimp campaign email

**Comment by pbiggar** [comment]
https://docs.darklang.com/changelog/release-9

**Comment by StachuDotNet** [comment]
https://youtu.be/62DXYN203UM release discussion here. Currently private.
FYI I've gone into the youtube editor to remove the first minute of the video, but it takes youtube a while to process.
