### ISSUE TITLE
Darklang Release 10

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/docs#333]
for the work in January 2023

- [ ] create changelog entry/docs update
  - [x] add changelog page
    - [x] create a new `release-n.md` page in [/docs/changelog](/docs/changelog)
    - [x] use [the `dark-changelog` canvas](https://darklang.com/a/dark-changelog) to fill in a draft of the changelog this gather PRs merged throughout the month
    - [x] create headers; move bullets to appropriate headers
    - [x] merge similar bullets where relevant
    - [x] revise wording
    - [ ] find images (esp gifs) to show behavior
    - [ ] review each item and fill in changelog with images, diagrams, screen recordings, etc.
    - [x] were there any emergencies (i.e. service interruptions) throughout the month? are they worth documenting within the changelog or during our normal release cycle? Check `#status` and `#operations` in Discord, for reference.
    - [ ] update docs with anything we've done in the past month (if there's not much, just edit it in the main PR; otherwise updating docs in separate PRs might make sense)
  - [x] add reference to new page in sidebar
  - [x] add link to new page from [/docs/changelog.md](/docs/changelog.md)
  - [ ] [tag repo](https://github.com/darklang/dark/tags)
  - [ ] merge changelog and docs updates
- [ ] Video/audio of release discussion
  - [ ] schedule twitch conversation
    - [ ] announce schedule
  - [ ] record for youtube
  - [ ] upload to YT (unlisted)
  - [ ] edit YT video
  - [ ] publish to youtube
  - [ ] add link to changelog
- [ ] prepare drafts
  - [ ] draft blog post
    - [ ] review each changelog item to see if it should be highlighted
    - [ ] consider
      - [ ] what were the major themes of the month?
      - [ ] what's immediately useful to our users?
      - [ ] what interesting technical challenges did we face?
    - [ ] can we link to any new docs/features?
    - [ ] can we include any images or gifs?
    - [ ] what header image should we use? with link
    - [ ] include commented out links to Lobstrs, HN, Twitter, Mastodon, reddit, youtube, twitch, discord
  - [ ] draft email
    - [ ] create mailchimp campaign
    - [ ] write draft
  - [ ] draft
        [tweet](https://twitter.com/darklang)/[toot](https://devtools.social/@darklang)
  - [ ] draft [HN](https://news.ycombinator.com/submit)
  - [ ] draft [r/darklang](https://reddit.com/r/darklang)
  - [ ] draft [Lobstrs](https://lobste.rs/stories/new)
  - [ ] draft [discord #announcements](https://discord.com/channels/1015413734153388094/1015432022489043025)
  - [ ] draft [Slack #announcements](https://darkcommunity.slack.com/archives/CP22G0GSJ)
- [ ] publish blog post
- [ ] post to socials
  - [ ] send tweet
  - [ ] send toot
  - [ ] post HN
  - [ ] post r/darklang
  - [ ] post Lobstrs
  - [ ] post discord
  - [ ] post slack \#announcements
- [ ] update blog post with links
  - [ ] twitter
  - [ ] mastodon
  - [ ] reddit
  - [ ] HN
  - [ ] Lobstrs
  - [ ] discord
- [ ] backlink to blog
  - [ ] changelog
  - [ ] youtube
- [ ] send mailchimp campaign email

**Comment by shawntax** [comment]
Hello! I'm not sure if the current version of blog.darklang.com is open-source, but just a heads-up that the [link](https://blog.darklang.com/darklang-release-10/) to it from [the docs page](https://docs.darklang.com/changelog/release-10) is resulting in a 404.

**Comment by StachuDotNet** [comment]
Hi there @shawntax - the blog post corresponding to this release is not yet written and thus not yet published! So that's expected. :)

Ah - but now I see - the published changelog references the (non-existent) blog post. We'll work on that, thanks for the reminder.

**Comment by pbiggar** [comment]
I think we don't plan to do any more with this?
